# Using Tensorflow as Numpy

**Tensorflow APi revolves around "tensors", which is usually a multidimensional array, but it can also hold a scalar(a simple values , such as 42).<br><br>Tensors will be important when  we create ( custom cost function, custom metics, custom layers) and more.**

# Tensors and Operations


In [1]:
import tensorflow as tf

In [2]:
 # we can create a tensor with (tf.constant).
    
tf.constant([[1.,2.,3.],[4.,5.,6.]])#matrix


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
tf.constant([3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

**just like ndarray, a tf.Tensor has a shape and a data type(dtype)**

In [5]:
t= tf.constant([[1,2,4],[5,7,8]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [5, 7, 8]])>

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.int32

**Indexing works much like Numpy**

In [8]:
t[1:]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[5, 7, 8]])>

In [9]:
t[:,:1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [5]])>

In [10]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [7, 8]])>

# Keras Low-Level API

**keras has its own low level Api(square(),exp(),and sqrt()).**

In [11]:
from tensorflow import keras
k=keras.backend

In [12]:
k.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4, 16],
       [25, 49, 64]])>

In [13]:
k.transpose(t)+10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 15],
       [12, 17],
       [14, 18]])>

# Tensors and Numpy

**Tensors play nice with Numpy :you can create a tensor from a Numpy array, and vice-versa. You can even apply Tensorflow operations to Numpy arrays and Numpy operations to tensor**

In [14]:
import numpy as np

In [15]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [16]:
a.dtype

dtype('int32')

In [17]:
b= tf.constant(a)
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [18]:
t.numpy()

array([[1, 2, 4],
       [5, 7, 8]])

In [19]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  9, 16])>

In [20]:
np.square(t)

array([[ 1,  4, 16],
       [25, 49, 64]], dtype=int32)

**When you create a (Tensor from a Numpy array), make sure to set dtype=tf.float32**

  # Type Conversions
  
  **Tensorflow does not perform any type conversions automatically.<br>You can't add a float tensor and an integer tensor**

In [21]:
tf.constant(3.) + tf.constant(4)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: add/

In [22]:
tf.constant(3.) + tf.constant(4.)

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [23]:
tf.cast(5.,tf.float32) + tf.constant(6.)

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

# variables

**(Tf.Tensor) values we've seen so far are immutable.You can't modify them.
So we use (Tf.variable)**

In [24]:
v=tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [25]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

# Others Data Structures

# Strings

**It's important to note that a (tf.string) is atomic, meaninig that its length does not appear in the tensor's shape. Once you convert it to a unicode tensor the length appears in the shape**

In [26]:
tf.constant("hello world")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [27]:
tf.constant("cafe")

<tf.Tensor: shape=(), dtype=string, numpy=b'cafe'>

In [28]:
tf.Variable("cd") + tf.Variable("dd")

<tf.Tensor: shape=(), dtype=string, numpy=b'cddd'>

In [29]:
tf.add("helo","world")

<tf.Tensor: shape=(), dtype=string, numpy=b'heloworld'>

In [30]:

tf.constant("cafe")

<tf.Tensor: shape=(), dtype=string, numpy=b'cafe'>

In [31]:
u = tf.constant([ord(a) for a in "cafe"])
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 101])>

# Ragged Tensor

In [32]:
tf.ragged.constant([[1,2,3],[4,5,6]])

<tf.RaggedTensor [[1, 2, 3], [4, 5, 6]]>

# Customizing Models and Training Algorithms

Let's start by creating a custom loss function, which is a simple and cmmon use case.

# Custom Loss Functions

Suppose you want to train a regression model,but your traininig set is a bit noisy(outliers). You start by trying to clearn up your dataset by removing or fixing the outliers,but dataset is still noisy. <br>
It's time we use (Huber Loss()).

In [ ]:
def huber_fn(y_train, y_pred):
    error = y_true-y_pred
    is_small_error = tf.abs(error)<1
    squared_loss = tf.square(error) /2
    linear_loss = tf.abs(error) - 0.5  
    return tf.where(is_small_error, squared_loss, linear_loss)

In [ ]:
plt.figure(figsize=(8,3.5))
z = np.inspace(-4,4,200)
plt.plot(z,huber_fn(0,z),'b-', linewidth=2, label="huber($z$)")
plt.plot(z, z**2/2, "b:", linewidth =1, label = r"$\frac{1}{2}z^2$"")
plt.plot([-1, -1], [0, huber_fn(0., -1.)], "r--")
plt.plot([1, 1], [0, huber_fn(0., 1.)], "r--")
plt.gca().axhline(y=0, color='k')
plt.gca().axvline(x=0, color='k')
plt.axis([-4, 4, 0, 4])
plt.grid(True)
plt.xlabel("$z$")
plt.legend(fontsize=14)
plt.title("Huber loss", fontsize=14)
plt.show()

In [ ]:
input_shape = X_train.shape[1:]

model = keras.models.Sequential([
    keras.layers.Dense(30,activation = "selu", kernel_initializer = "lecun_normal",input_shape = input_shape),
    keras.layers.Dense(1)
])

In [ ]:
model.compile(loss= huber_fn, optimizer = "nadam", metrics = ["mae"])0

In [ ]:
model.fit(X_train,y_train,epocs=2,validation_data=(X_valid_scaled,y_valid))

But what happens to this custom loss when you save the model?

# Saving and Loading Models that contain custom Components

In [ ]:
model.save("my_model.h5")

In [ ]:
model = keras.models.load_model("my_model.h5",
                               custom_objects={"huber_fn":huber_fn})

In [ ]:
model.fit()

But if you want a different threshlod? One solution is to create a function that creates a configured loss function.

In [ ]:
def create_huber(threshold=1.0):
    def huber_fn(y_true,y_pred):
          error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold
        squared_loss = tf.square(error) / 2
        linear_loss  = threshold * tf.abs(error) - threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

In [ ]:
model.compile(loss=create_huber(2.0),optimizer="nadam",metrics=["mae"])

In [ ]:
model.fit()

In [ ]:
model.save("my_model_threshold.h5")

But unfortunately , When we save the model the threshold will not saved. This means that you will have to specify the threshold value when loading the model
(note that the name to use is "huber_fn", which is the name of the function you gave  Keras,not the name of the function that created it.)

In [ ]:
#when we save custom model that can't save custom threshold, so when we load our model we have to call that threshold value.
model = keras.models.load_model("my_model_threshold.h5",
                               custom_objects={"huber_fn": create_huber(2.0)})

We can solve this by creating a subclass of the **(keras.losses.Loss)** class, and then implementing its **(get_config())** method.